# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'contact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for contact
  pod 'R.swift'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxRealm'
  pod 'IQKeyboardManagerSwift'
  
  target 'ListingTests' do
      # Pods for testing
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'RxNimble'
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
